name: CI

on:
  push:
    tags:
      - "*.*.*"

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  fly-deploy:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: my_app_test
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    env:
      MIX_ENV: test
      GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v2
    - name: Install Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: '1.12.1'
        otp-version: '24.0.2'
          
    - uses: actions/cache@v1
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
        restore-keys: |
          ${{ runner.os }}-mix-
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - run: mix local.rebar --force
    - run: mix local.hex --force
    - run: mix deps.get
    - run: npm install --prefix assets
    - run: npm run deploy --prefix assets
    - run: mix test
    
    - uses: superfly/flyctl-actions@1.1
      with:
        args: "deploy"
